### ISSUE TITLE
IotHubUnauthorizedAccess error

### ISSUE THREAD

**Issue by ppparihar** [MattHoneycutt/ps-create-iot-solutions#1]
I'm flowing the device-provisioning-sample along with the Pluralsight course but while run the sample code I'm getting following error 
`Unhandled Exception: Microsoft.Azure.Devices.Provisioning.Client.ProvisioningTransportException: AMQP transport exception ---> Microsoft.Azure.Amqp.AmqpException: {"errorCode":401002,"trackingId":"009f4f3a-a461-4257-9597-6c1bf0528b6b","message":"IotHubUnauthorizedAccess","timestampUtc":"2019-10-10T09:37:22.7666564Z"}
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.AmqpClientConnection.OpenAsync(TimeSpan timeout, Boolean useWebSocket, X509Certificate2 clientCert, IWebProxy proxy)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerAmqp.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---`

**Comment by duochen** [comment]
I had the same issue,  I thought the code has been updated but the problem is still there.

Unhandled Exception: Microsoft.Azure.Devices.Provisioning.Client.ProvisioningTransportException: AMQP transport exception ---> Microsoft.Azure.Amqp.AmqpException: {"errorCode":401002,"trackingId":"0fb198db-c1ee-46f9-9be4-9a4e5bf09f1f","message":"IotHubUnauthorizedAccess","timestampUtc":"2021-01-29T15:56:09.0260221Z"}
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.AmqpClientConnection.OpenAsync(TimeSpan timeout, Boolean useWebSocket, X509Certificate2 clientCert, IWebProxy proxy)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerAmqp.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerAmqp.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken)
   at DeviceProvisioningSample.Device.Provision() in D:\myproject\Samples-Azure-IoT\Pluralsight\microsoft-azure-iot-solutions-creating\04\demos\demos\ps-create-iot-solutions-master\device-provisioning-sample\Device.cs:line 33
   at DeviceProvisioningSample.Program.Main(String[] args) in D:\myproject\Samples-Azure-IoT\Pluralsight\microsoft-azure-iot-solutions-creating\04\demos\demos\ps-create-iot-solutions-master\device-provisioning-sample\Program.cs:line 26
   at DeviceProvisioningSample.Program.<Main>(String[] args)

**Comment by RavitejaGali** [comment]
hallo Parihar,

is this problem resolved?
